apiVersion: v1
kind: Service
metadata:
  name: sales-and-marketing
  labels:
    app: sales-and-marketing
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sales-and-marketing