server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: product-info
          uri: http://localhost:8082
          predicates:
            - Path=/products/**, 
        - id: sales-and-marketing
          uri: http://localhost:8083
          predicates:
            - Path=/sales/**, 
        - id: expert-advice
          uri: http://localhost:8085
          predicates:
            - Path=/experts/**, 
        - id: customer-service
          uri: http://localhost:8088
          predicates:
            - Path=/customerServices/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: product-info
          uri: http://productInfo:8080
          predicates:
            - Path=/products/**, 
        - id: sales-and-marketing
          uri: http://salesAndMarketing:8080
          predicates:
            - Path=/sales/**, 
        - id: expert-advice
          uri: http://expertAdvice:8080
          predicates:
            - Path=/experts/**, 
        - id: customer-service
          uri: http://customerService:8080
          predicates:
            - Path=/customerServices/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
